define table = 
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(2, 'TonnisWO', 'tvOhGcCQ', 2, 3, 2, 2, 5, 2,93, 2,74, 2,58);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(1, 'zibJuHQT', 'zcXDPqdL', 1, 2, 1, 4, 3, 2,39, 2,06, 1,79);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(3, 'VVEUvfWu', 'LOWeQmQT', 4, 4, 4, 1, 2, 3,06, 2,8, 2,51);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(4, 'giAGgbSv', 'WrlgEnjS', 3, 2, 1, 2, 4, 2,35, 2,11, 1,89);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(99, 'matiq', 'qqq', 1, 1, 1, 1, 1, 1, 1, 1);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(6, 'rSJOjwtW', 'QsYYjfIJ', 4, 4, 1, 2, 3, 2,99, 2,67, 2,3);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(7, 'JFOhjabT', 'XIuDtmvx', 2, 5, 3, 4, 2, 3,27, 3,1, 2,93);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(8, 'WIwvXuyE', 'dEKTuZCk', 4, 5, 3, 1, 4, 3,5, 3,18, 2,78);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(9, 'UmLUhWFi', 'VmvyJFcI', 4, 1, 3, 1, 2, 2,29, 2,03, 1,8);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(11, 'cNPvCFro', 'VgLElZQo', 1, 1, 2, 4, 1, 1,91, 1,67, 1,5);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(12, 'LnmocFiX', 'RpgttmEZ', 2, 5, 2, 2, 3, 3,04, 2,91, 2,8);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(13, 'xATGpJoi', 'UhbYnRqV', 5, 2, 5, 3, 3, 3,72, 3,59, 3,47);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(14, 'OaxILWim', 'xbMTuScw', 3, 3, 3, 3, 3, 3,03, 3,01, 2,99);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(15, 'pcxjORev', 'dnMEaGLq', 3, 2, 3, 2, 5, 3,03, 2,86, 2,7);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(16, 'nbtBjuAv', 'tYMISyoP', 4, 3, 2, 2, 5, 3,17, 2,94, 2,72);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(17, 'CCTekIEE', 'tGNrsrLs', 4, 2, 1, 3, 5, 2,84, 2,43, 2,05);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(18, 'mFKtptSq', 'LZKSOSMB', 4, 2, 2, 1, 2, 2,05, 1,91, 1,8);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(19, 'kRDUKiyZ', 'rPmbJwsN', 1, 4, 4, 2, 2, 2,56, 2,27, 2,05);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(21, 'njHKbPoV', 'jDBbooLA', 4, 2, 4, 4, 3, 3,46, 3,37, 3,27);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(22, 'LbtrCpHx', 'fEGNWXwv', 3, 4, 3, 2, 3, 2,96, 2,89, 2,83);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(23, 'SGjgMbHS', 'JjwJXelw', 4, 2, 3, 1, 4, 2,99, 2,73, 2,44);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(24, 'xZZYjgbg', 'XZsYEsnV', 2, 3, 5, 4, 3, 3,52, 3,42, 3,31);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(25, 'oblzSqWq', 'ksdcHrqP', 5, 3, 5, 4, 5, 4,28, 4,17, 4,04);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(26, 'iopwsdGv', 'JUjUNwrP', 2, 4, 5, 4, 2, 3,27, 2,96, 2,65);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(27, 'AgjPUAgV', 'ffhfkkUO', 5, 3, 2, 2, 2, 2,84, 2,7, 2,58);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(28, 'FFZUWlRh', 'bDANtxIp', 1, 2, 5, 4, 3, 3,16, 2,87, 2,59);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(29, 'pETpcCFP', 'lAWYkUDU', 3, 2, 2, 4, 3, 2,83, 2,71, 2,58);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(30, 'tZenZNjY', 'sqovtuhc', 3, 1, 3, 4, 3, 2,81, 2,59, 2,3);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(31, 'znUROdJQ', 'LjCMHceh', 3, 4, 3, 2, 1, 2,66, 2,5, 2,32);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(32, 'gtRGMvpr', 'xEbWqKoI', 3, 1, 5, 5, 1, 2,92, 2,44, 2,01);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(33, 'ExRZaTiX', 'WqCKUGzP', 5, 4, 3, 2, 3, 3,5, 3,39, 3,29);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(34, 'iaNAPaUF', 'rbzuWFUk', 2, 1, 3, 2, 4, 2,52, 2,31, 2,13);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(35, 'IZhWGRuk', 'LhGtoFNs', 4, 4, 2, 3, 5, 3,67, 3,58, 3,49);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(36, 'QMIfFwkh', 'mAkoZEgf', 4, 4, 2, 2, 3, 2,88, 2,7, 2,53);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(37, 'lQEHOyAv', 'zHisCofd', 5, 5, 4, 1, 2, 3,33, 2,9, 2,44);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(38, 'zHLaUANd', 'vtwabYaH', 2, 4, 1, 5, 3, 2,84, 2,52, 2,24);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(39, 'fDYTDLUk', 'rUlJYLlE', 3, 1, 5, 4, 2, 3,16, 2,78, 2,35);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(41, 'ERHLgtSB', 'asVbXxOs', 5, 1, 4, 4, 2, 3,22, 2,94, 2,64);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(42, 'qMETvGqw', 'CHyMylQA', 5, 3, 2, 3, 3, 3,08, 2,91, 2,75);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(43, 'ZbhNlRng', 'UaiuTYMO', 4, 2, 5, 3, 5, 3,56, 3,38, 3,19);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(44, 'mrGrYian', 'WXjACExV', 1, 3, 5, 3, 1, 2,62, 2,21, 1,84);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(45, 'xaWYMntx', 'KMhPAQzQ', 2, 3, 3, 2, 3, 2,66, 2,56, 2,45);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(46, 'Ucmspeoo', 'SHuzWLEt', 4, 3, 4, 2, 2, 3,02, 2,86, 2,7);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(47, 'lXzASsWK', 'RqvsQpPB', 4, 3, 4, 4, 3, 3,5, 3,42, 3,34);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(48, 'KitTuAVJ', 'ataiPVvf', 2, 1, 1, 1, 4, 2, 1,72, 1,53);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(49, 'LYjOYZFz', 'kNDVOFSA', 2, 5, 5, 3, 4, 3,79, 3,64, 3,47);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(50, 'zFQowEOx', 'slRYbZHS', 3, 3, 2, 2, 4, 2,88, 2,83, 2,78);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(51, 'vIfAPqXy', 'ekvlAzUo', 3, 5, 4, 4, 2, 3,4, 3,27, 3,13);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(52, 'JocchdNl', 'DpOYQAVG', 3, 3, 2, 4, 2, 3, 2,91, 2,84);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(53, 'dmRtQCdj', 'QLuWpYqJ', 2, 5, 4, 5, 4, 3,94, 3,74, 3,5);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(54, 'DBvGHMOX', 'dPudiCEf', 2, 1, 5, 2, 2, 2,35, 2,1, 1,9);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(55, 'aemPaOWA', 'ZHnBpjtd', 1, 2, 5, 3, 3, 2,95, 2,74, 2,53);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(56, 'tuxbUdHD', 'nhUrzTbK', 2, 4, 4, 4, 3, 3,39, 3,21, 2,98);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(57, 'eEeWLKsL', 'xwnTeCyQ', 3, 2, 4, 3, 2, 2,65, 2,51, 2,38);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(58, 'RGGczMBO', 'dyLwJQGI', 3, 3, 1, 1, 3, 2,23, 2,05, 1,86);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(59, 'HLXqQpEM', 'gdCcRHEr', 3, 3, 3, 1, 4, 2,94, 2,74, 2,49);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(60, 'uFDamWfr', 'aTJPsIXw', 3, 3, 4, 4, 3, 3,43, 3,37, 3,31);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(61, 'GQSAAohw', 'LDVJthyt', 4, 2, 4, 3, 2, 3,15, 3,02, 2,88);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(62, 'vWKzNoQj', 'DsuIpvFr', 3, 2, 2, 3, 3, 2,44, 2,39, 2,33);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(63, 'jNrNmdfM', 'GioBcGeH', 2, 4, 4, 4, 2, 2,94, 2,77, 2,58);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(64, 'TtROlpic', 'EVAmNJIo', 2, 4, 4, 3, 4, 3,55, 3,45, 3,35);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(65, 'EVAmxMpi', 'haCceyzg', 3, 3, 5, 5, 3, 3,77, 3,67, 3,59);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(66, 'twxKRkEC', 'QHwvrGrd', 5, 2, 4, 1, 2, 2,71, 2,38, 2,07);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(67, 'gzzluEXX', 'foovVPnl', 1, 3, 3, 2, 3, 2,34, 2,22, 2,09);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(68, 'dSITHDTD', 'EtOANfqC', 4, 1, 3, 5, 3, 3,34, 2,97, 2,49);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(69, 'LdLidxrF', 'ByAbnzHC', 4, 4, 2, 4, 4, 3,77, 3,66, 3,53);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(70, 'fBTlXxcB', 'krnaqLwF', 1, 5, 2, 2, 4, 2,85, 2,55, 2,29);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(71, 'ggOHPkoL', 'zbvuKwBJ', 2, 2, 1, 2, 1, 1,78, 1,74, 1,69);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(72, 'coMYsKUH', 'WBpyAmRD', 2, 3, 4, 4, 4, 3,4, 3,26, 3,1);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(73, 'eCkbzWbn', 'uGhGPEZY', 3, 4, 5, 1, 5, 3,52, 3,18, 2,76);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(74, 'xciLOWkG', 'OcMmdEoi', 3, 3, 2, 4, 1, 2,58, 2,32, 2,06);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(75, 'dRuXZPoK', 'PlvffqRG', 5, 3, 1, 3, 4, 3,42, 3,13, 2,78);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(76, 'gjmvyEFd', 'DNkHwVBx', 2, 2, 4, 1, 5, 2,71, 2,36, 2,09);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(77, 'tHDDkRvT', 'DflKcZQy', 1, 3, 4, 3, 1, 2,37, 2,08, 1,81);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(78, 'WhRgcrqt', 'iIdLDkUD', 3, 1, 2, 1, 5, 2,56, 2,21, 1,91);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(79, 'OpKXuzEQ', 'DUJETakv', 4, 2, 2, 4, 2, 2,84, 2,65, 2,47);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(80, 'PiVfgPhG', 'PQhsFucQ', 5, 3, 1, 1, 5, 2,99, 2,49, 2,02);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(82, 'vaDgkLep', 'FgngBMgA', 1, 1, 2, 3, 5, 2,41, 2,09, 1,83);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(83, 'jAaOfzdg', 'FqplGTMP', 3, 4, 2, 5, 3, 3,37, 3,21, 3,05);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(84, 'aQjBkWGk', 'BezVYJGC', 3, 4, 4, 3, 4, 3,72, 3,69, 3,66);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(85, 'rmGsRnUl', 'GblMNlkx', 2, 2, 2, 3, 3, 2,47, 2,41, 2,35);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(86, 'bPzrJccg', 'vTcQxThW', 3, 2, 1, 2, 3, 2,17, 2,01, 1,84);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(87, 'OrkFVeWD', 'Qvskejvj', 3, 3, 3, 4, 3, 2,99, 2,96, 2,94);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(88, 'WZFujHFa', 'DmPyPgld', 3, 5, 4, 4, 2, 3,47, 3,31, 3,15);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(89, 'gyMLhpfF', 'KizIbIbr', 2, 2, 4, 3, 3, 2,87, 2,74, 2,63);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(90, 'OLYVHxHd', 'tWPmZhHu', 2, 5, 4, 2, 2, 2,85, 2,64, 2,45);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(91, 'LNXZHshK', 'WfIjxBGJ', 3, 4, 2, 4, 3, 3,33, 3,25, 3,18);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(92, 'xIhPVhQK', 'zVtWqnTR', 2, 2, 4, 1, 3, 2,35, 2,19, 2,02);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(93, 'dUQtjBSd', 'bKPwHbjF', 1, 2, 3, 4, 4, 2,83, 2,61, 2,36);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(94, 'tVwCPFYe', 'GvMWlqri', 4, 2, 4, 1, 1, 2,71, 2,35, 2,05);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(95, 'wdVGvekJ', 'GWNJhgjV', 4, 5, 2, 3, 3, 3,27, 3,09, 2,9);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(96, 'ywGoqJiO', 'RrogZzQa', 2, 2, 2, 2, 4, 2,46, 2,32, 2,22);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(97, 'PdsGHIFq', 'woHXgkTf', 4, 3, 2, 5, 4, 3,55, 3,37, 3,17);
INSERT INTO &table (ID, IMIE, NAZWISKO, OCENA_POLSKI, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZYKA, SREDNIA_ARYTMETYCZNA, SREDNIA_GEOMETRYCZNA, SREDNIA_HARMONICZNA)
  VALUES(98, 'mwMZHTHh', 'NFXrhEDP', 4, 2, 5, 3, 5, 3,7, 3,48, 3,21);
COMMIT;
